/**
 * MongoDB $project stage for social_messages.
 * Use in aggregate pipeline to limit returned fields.
 * To override at runtime, assign to projectSocialMessage or use a dedicated config service.
 */
export const PROJECT_SOCIAL_MESSAGE: Record<string, 0 | 1 | Record<string, 0 | 1>> = {
  publisheddate: 1,
  publishedAtUnix: 1,
  visibility: 1,
  status: 1,
  code: 1,
  account_ids: 1,
  channel: 1,
  content: {
    keyword: 1,
    from: 1,
    user: 1,
    profileImg: 1,
    author: 1,
    author_img: 1,
    quote_count: 1,
    reply_count: 1,
    retweet_count: 1,
    favorite_count: 1,
    bookmark_count: 1,
    view: 1,
    pageName: 1,
    message: 1,
    text: 1,
    username: 1,
    full_text: 1,
    file_id: 1,
    file_attachment: 1,
    title: 1,
    topic: 1,
    content: 1,
    caption: 1,
    channel: 1,
    cover_image: 1,
    color_bw: 1,
    statistics: 1,
    image: 1,
    snippet: 1,
    gallery: 1,
    id: 1,
    post_id: 1,
    pt_id: 1,
    id_service2: 1,
    issue_no: 1,
    comment_id: 1,
    full_picture: 1,
    media_type: 1,
    media_url: 1,
    media_length: 1,
    thumbnail_url: 1,
    link: 1,
    permalink: 1,
    permalink_url: 1,
    page_position: 1,
    program_name: 1,
    page_ratio: 1,
    public_date_time: 1,
    published_date_time: 1,
    publisher: 1,
    extended_entities: 1,
    quoted_status: 1,
    recognition: 1,
    engagement: 1,
    attachment: 1,
    sentiment: 1,
    snippetChannel: 1,
    easyModeTags: 1,
    gender: 1,
    display_name: 1,
    frequency: 1,
    circulation: 1,
    ad_rate: 1,
    ad_value: 1,
    pr_value: 1,
    section: 1,
    year: 1,
    no_news: 1,
    position_news: 1,
    column_inch: 1,
    length: 1,
    color: 1,
    code_news: 1,
    watch_type: 1,
    updated_time: 1,
    id_str: 1,
    channelImageURL: 1,
    gcp: 1,
    news_sections: 1,
  },
  domain: 1,
  statusMessage: 1,
  intent: 1,
  speakerType: 1,
  postFormat: 1,
  keywords: 1,
  sentiments: 1,
  tags: 1,
  sendTo: 1,
  engagementOvertime: 1,
  totalEngagement: 1,
  totalView: 1,
  trackingPost: 1,
  source: 1,
  follower: 1,
  provinceName: 1,
  place: 1,
  highlight_keyword: 1,
  highlight_junk_keyword: 1,
  display_name: 1,
  frequency: 1,
  circulation: 1,
  section: 1,
  year: 1,
  no_news: 1,
  position_news: 1,
  column_inch: 1,
  length: 1,
  color: 1,
  code_news: 1,
  watch_type: 1,
  updated_time: 1,
  center_data: 1,
  ai_detect: 1,
  rawContent: 1,
};

/** Current projection used in queries. Defaults to PROJECT_SOCIAL_MESSAGE; override via setProjectSocialMessage() if needed. */
let currentProjection = PROJECT_SOCIAL_MESSAGE;

export function getProjectSocialMessage(): Record<string, 0 | 1 | Record<string, 0 | 1>> {
  return currentProjection;
}

export function setProjectSocialMessage(
  value: Record<string, 0 | 1 | Record<string, 0 | 1>>,
): void {
  currentProjection = value;
}
