// src/modules/real-listening/common/constants/query-map.constant.ts

export const CHANNEL_GROUPS: Record<string, string[]> = {
  facebook: ['facebook-post', 'facebook-comment', 'facebook-subcomment'],
  twitter: [
    'twitter-tweet',
    'twitter-reply',
    'twitter-retweet',
    'twitter-quote',
  ],
  tiktok: ['tiktok-post', 'tiktok-comment', 'tiktok-subcomment'],
  youtube: ['youtube', 'youtube-post', 'youtube-comment'],
  instagram: ['instagram', 'instagram-comment'],
  pantip: ['pantip-post', 'pantip-comment'],
  blockdit: ['blockdit-post'],
  website: ['website-post'],
  webboard: ['webboard-post', 'webboard-comment'],
  newspaper: ['newspaper'],
  magazine: ['magazine'],
  radio: ['radio'],
  television: ['television'],
};

export const SORT_FIELD_MAP: Record<string, string> = {
  publisheddate: 'publishedAtUnix',
  totalEngagement: 'totalEngagement',
  totalView: 'totalView',
  follower: 'follower',
};

export const LANGUAGE_REGEX_MAP: Record<string, string> = {
  th: '[ก-ฮ]',
  tha: '[ก-ฮ]',
  en: '[A-z]',
  eng: '[A-z]',
  mm: '[က-ဪ]',
  mya: '[က-ဪ]',
  bur: '[က-ဪ]',
  lo: '[ກ-ຮ]',
  lao: '[ກ-ຮ]',
  km: '[ក-ឳ]',
  khm: '[ក-ឳ]',
  vi: '[À-ỹ]',
  vie: '[À-ỹ]',
  zh: '[\\u4e00-\\u9fa5]',
  zho: '[\\u4e00-\\u9fa5]',
  ko: '[가-힣]',
  kor: '[가-힣]',
  ja: '[ぁ-ゟァ-ヿㇰ-ㇿ一-龯]',
  jpn: '[ぁ-ゟァ-ヿㇰ-ㇿ一-龯]',
};

export const LANGUAGE_SEARCH_FIELDS = [
  'content.from.name',
  'content.user.name',
  'content.user.username',
  'content.username',
  'content.message',
  'content.full_text',
  'content.content',
  'content.pageName',
  'content.text',
  'content.title',
  'content.caption',
  'content.topic',
  'content.snippet.title',
  'content.snippet.channelTitle',
  'content.snippet.description',
  'content.author',
  'content.gcp.ocr',
  'center_data.ai.ocr',
  'content.gcp.object.name',
  'ocr_text',
  'object_text',
  'center_data.topic',
  'center_data.message',
];

export const SIMPLE_IN_FIELDS = [
  'sentiments',
  'source',
  'provinceName',
  'speakerType',
  'intent',
  'tagsPr',
  'tagsRpt',
  'prnews',
  'prSentiment',
  'rptSentiment',
  'prStatusMessage',
  'rptStatusMessage',
  'prVisibility',
  'rptVisibility',
];
